### ISSUE TITLE
Generate video with ControlNet (pose/edge/depth)

### ISSUE THREAD

**Issue by yuanxion** [yuanxion/Text2Video-Zero#14]
Reference:
https://github.com/yuanxion/Text2Video-Zero

**Comment by yuanxion** [comment]
### Models/files cache

Download models/config files and cache them for local usage.
https://zhuanlan.zhihu.com/p/475260268

- git **lfs** install
https://blog.csdn.net/flyingluohaipeng/article/details/130788293
```
git clone https://huggingface.co/dreamlike-art/dreamlike-photoreal-2.0
mkdir dreamlike-art
mv dreamlike-photoreal-2.0/ dreamlike-art/
```

- [ ] fusing/stable-diffusion-v1-5-controlnet-openpose
**diffusion_pytorch_model.bin** can be downloaded from https://huggingface.co/fusing/stable-diffusion-v1-5-controlnet-openpose
- [ ] runwayml/stable-diffusion-v1-5
https://huggingface.co/runwayml/stable-diffusion-v1-5/

- huggingface_hub **snapshot_download**
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/dreamlike-art/dreamlike-photoreal-2.0/revision/main (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
```
Add `import os; os.environ['CURL_CA_BUNDLE'] = ''` to try downloading again, or try many times.
```
from huggingface_hub import snapshot_download
import os
os.environ['CURL_CA_BUNDLE'] = ''
snapshot_download(repo_id="dreamlike-art/dreamlike-photoreal-2.0")
```

**Comment by yuanxion** [comment]
### Server env

- OS: 18.04.6
- Python: 3.8
<img width="423" alt="image" src="https://github.com/yuanxion/Text2Video-Zero/assets/96522341/8cbb69a3-b9f1-4282-9cff-78f6f4ec5c4a">

Solved this issue by installing conda and create env with python 3.9.
```
CUDA_VISIBLE_DEVICES=0 python3 demo/demo-t2v.py
```

**Comment by yuanxion** [comment]
According to Xianfu, Change the resolution in the configuration to like "200*200" can pass the running, but maybe bad quality.

**Comment by xianfu92** [comment]
Sample script:

```
import torch
import os
from model import Model

model = Model(device = "cuda", dtype = torch.float16)
print(f'--> model {model}')

chunk_size = 2    # Default: 8
merging_ratio = 0 # Default: 0
resolution = 450  # Default: 512
params = {"chunk_size" : chunk_size, "merging_ratio" : merging_ratio, "resolution" : resolution}

# Pose
prompt = 'an astronaut dancing in outer space'
motion_path = '__assets__/poses_skeleton_gifs/dance1_corr.mp4'
out_path = f"./text2video_pose_guidance_{prompt.replace(' ','_')}.gif"

model.process_controlnet_pose(motion_path, prompt=prompt, save_path=out_path, **params)

# Edge
prompt = 'oil painting of a deer, a high-quality, detailed, and professional photo'
video_path = '__assets__/canny_videos_mp4/deer.mp4'
out_path = f'./text2video_edge_guidance_{prompt}.gif'

model.process_controlnet_canny(video_path, prompt=prompt, save_path=out_path, **params)

# Depth
prompt = 'oil painting of a deer, a high-quality, detailed, and professional photo'
video_path = '__assets__/depth_videos/deer.mp4'
out_path = f'./text2video_depth_control_{prompt}.gif'

model.process_controlnet_depth(video_path, prompt=prompt, save_path=out_path, **params)

```

**Comment by yuanxion** [comment]
Generated 40*40 resolution gif files with the above script provided by @XianFuWongIntel :

![text2video_pose_guidance_an_astronaut_dancing_in_outer_space](https://github.com/yuanxion/Text2Video-Zero/assets/96522341/a528ec81-e3e1-4e65-b5a6-f88e30b1c2a6)

![text2video_depth_control_oil painting of a deer, a high-quality, detailed, and professional photo](https://github.com/yuanxion/Text2Video-Zero/assets/96522341/09354e8b-5b0b-46f8-b406-0487e4a80456)
![text2video_depth_control_oil painting of a deer-fox, a high-quality, detailed, and professional photo](https://github.com/yuanxion/Text2Video-Zero/assets/96522341/d964b491-f7c7-4bd6-b23f-538abc2287a1)
![text2video_edge_guidance_oil painting of a deer, a high-quality, detailed, and professional photo](https://github.com/yuanxion/Text2Video-Zero/assets/96522341/382a70ad-1429-4c3d-9fb4-b7ba69c7d6fd)

**Comment by yuanxion** [comment]
Close this issue since addressed by PR https://github.com/yuanxion/Text2Video-Zero/pull/13.
